version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-final
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: finaldb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  pgdata:
